### ISSUE TITLE
image number zero

### ISSUE THREAD

**Issue by edsu** [DocNow/dnflow#30]
The image numbers in the similarity report are all zero. This was working fairly recently so there must've been  breaking change recently.

![screen shot 2016-08-19 at 4 44 52 pm](https://cloud.githubusercontent.com/assets/33829/17823788/66932700-662c-11e6-8bdc-17dc32905705.png)

**Comment by edsu** [comment]
@dchud I think I caused this. If you have any spare cycles could you help me identify what the problem is?

**Comment by dchud** [comment]
The way it's written now `media-graph.json` can arrive prior to `count-media.csv`, which would trigger the image rendering before the counts are available.  It's hard to replicate reliably because these two responses could return in any order.  This also explains why it looks fine most of the time.

Simplest solution is not to trigger the image rendering before the counts are in hand.
